language: java
sudo: false
notifications:
  slack:
    secure: WzdS5sSSQziwbZwqW8nCddRGC8SSrgcPyVn9NbV2MOkqa4mFawQOL05CCOc0RfV7otCCqxsDqXAehuyKzEVA8VrQ1g10Eelppbnv9WxDYzIj1M2MPmyo4RzHK6+aw0KRIujufgYQdxit+N/J2xATnUy+3hiXBQprCnIGXYaNk2w=
  hipchat:
    rooms:
      secure: Qd1hPi8dw+Bm16TxJE/v7BJGcGPl/j4AIQDK8sytP6+JX93Z/M/gMclcq3xQta9y/DQGof67vYSZe3Hb5hHirPENC2QL8sFcff4SSUzulNfug5DYaOtGzw6ugcqbUMSSFfuQSeDQZAx2zx8kjHqRFVFPejfMllooxVoLLiGqVGSVwiwisYEuGv5Y7uNEUt80iwJ5MMELKluD+i+0HgSf0xrLkIMXa5+GD98O8xAPmfwCaB0IaNwmJmdof1JhHNtc2oPGMoByTI4MB9YqePTj/tXMVTZxjFXqK1V//udDObjFoWib6D3iWTByk/lb8ZAE0mRyD9do1/Ad/sfCIXpn5pfXyNTByzX6LZ3sH1QbZ8wPSlH3FpwlxTrXKiB3vmGPpQKUee5YL2AYmCvHWkpy1m38JW3DZwDJZj6ZlAKENIMFXoUPcNGGjbgbM4+83qhx+qCwDSWpBw3UnVQeSwvSV1ymlvbDWUSd//AmP00vo7AJePvuv47ZiwqjDg8lhTkIPms7yaMy6xoZLqGeboLRMnSwNkLBq50RmwO6ELDfr12Yh6KzG90RnMT0L8JxVIwv1l5pUIb5z77shjwppmmxXESUa4EcrGpXWQ+xBftxR4vUCMIl4emdgGzQg9u+eOKofJuvlusCkUToa795fFkJJlH0A8Lhin0CsraJ9HuVKo8=
deploy:
  provider: releases
  api_key:
    secure: Hnm0cEFMIdOXaPkCMXKf4iudar++HVxmZBjBIE3gS+X6KrA1InaV/ZdWtdM3XBAiDCvQhzLAaTerNxoChY2IlPHZRChvtzdP8Gr9CfOInJXb0N44+gJrVsX3h+uCA1x16iXLRzklVuzYDrwviJexrCedFhquW9oy6e1YB05wBioGfS9K9kN2BHzcFfFWY/CE4OGumI7GPUKsp1mKbcgXgWl1VJXW+rfX7oNm5mwB9JIjXYuit2Eb7XnnHQ091Q9NAE/e9ZzL9h3sV/c/oR88sCWtSecYu6t/FG38fsrlKDj2WsuqHMiO0f81gwe10RY+nb4FpZBvDsvA5KkiPwDaFdSR+rmXvmDqQ1H2E2bl6Oc33GZaZBKmqxr36J3PPjILEq0fhUOfdfnASBacdVCXLvaW8aEvKRgN3AYiohfZlrJNiDbWisKkiz1gUdla99sg6UwGBZzX5ZCdUHVWdBPOp4pmdvSkJJyemgEmUAe/qPE9PEKfYCOppI3OtPluAeDqUAJBC0X//UMLL/+/XJ575sPbNLLuYe239zZi/gY9Ct5POSUld7xibkO4ucsRr7nVxJYe24tdvU1xil819sWDKfwt3w/Ujqw7k/4e2pQfjp1XTe1j7LW6+++lRxckWzCbZq/id2M7HL8qlKSabxB1LrEUh3bClJPz9DgjVME3TuA=
  file: build/libs/xlr-chef-plugin-1.1.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-chef-plugin
