language: java
sudo: false
notifications:
  slack:
    secure: WzdS5sSSQziwbZwqW8nCddRGC8SSrgcPyVn9NbV2MOkqa4mFawQOL05CCOc0RfV7otCCqxsDqXAehuyKzEVA8VrQ1g10Eelppbnv9WxDYzIj1M2MPmyo4RzHK6+aw0KRIujufgYQdxit+N/J2xATnUy+3hiXBQprCnIGXYaNk2w=
  hipchat:
    rooms:
      secure: Qd1hPi8dw+Bm16TxJE/v7BJGcGPl/j4AIQDK8sytP6+JX93Z/M/gMclcq3xQta9y/DQGof67vYSZe3Hb5hHirPENC2QL8sFcff4SSUzulNfug5DYaOtGzw6ugcqbUMSSFfuQSeDQZAx2zx8kjHqRFVFPejfMllooxVoLLiGqVGSVwiwisYEuGv5Y7uNEUt80iwJ5MMELKluD+i+0HgSf0xrLkIMXa5+GD98O8xAPmfwCaB0IaNwmJmdof1JhHNtc2oPGMoByTI4MB9YqePTj/tXMVTZxjFXqK1V//udDObjFoWib6D3iWTByk/lb8ZAE0mRyD9do1/Ad/sfCIXpn5pfXyNTByzX6LZ3sH1QbZ8wPSlH3FpwlxTrXKiB3vmGPpQKUee5YL2AYmCvHWkpy1m38JW3DZwDJZj6ZlAKENIMFXoUPcNGGjbgbM4+83qhx+qCwDSWpBw3UnVQeSwvSV1ymlvbDWUSd//AmP00vo7AJePvuv47ZiwqjDg8lhTkIPms7yaMy6xoZLqGeboLRMnSwNkLBq50RmwO6ELDfr12Yh6KzG90RnMT0L8JxVIwv1l5pUIb5z77shjwppmmxXESUa4EcrGpXWQ+xBftxR4vUCMIl4emdgGzQg9u+eOKofJuvlusCkUToa795fFkJJlH0A8Lhin0CsraJ9HuVKo8=
deploy:
  provider: releases
  api_key:
    secure: GXmtPA/ILOU0docT2JYkQrypUUvN9u1kLaMzE4gKrt2bUWBshTfMFSMdLnmWbFL7pspLz3Sg7aR0SpFDV6E7oXPW3jlnYHUj/X0u7FpHfepqYsIKaRvFHgGpcv2B6RIfzOJrtZUKnFFbOkyQ9kfDejnaq7wm6n/RmivmUnp+ZXvoHWnl6pAeBhJ3SKmrEp3zmytBlu99/D8pfyOnBesZATnH6IHNi9S5s3fgt7Gx3hBwCmaToi68donNSNTFS+yf/HFzEilyNsyhpdq2FUY36mki3a+EVpQutt3hqT8VkY1S4pYocBUjjZm9sYGJbUu9BsoMdYBTSjntJ5psngRrAIbE+kj1enJautCbcCUtyQpXgabGXBMcAS81SF4ZSZoaBOZedVUKm7t9dcySiN2az3amOz2kQhs6YhB4gxbY4ExUxOX8jF1vISGA4EjDyG05xqJzoU+r0wlIrfZ2NTGMApc411nhCOVxWiulVDQs8y8DlD8w3bgvbfmAxByfDSWXeETnWyGokrfeaTVKpkrHs5zz7AZ1HGClykB4IBpEPsw1ChMBDtxmpRD+V1GhKa0NDedUdl9QECst3Sy/aSbSUOgq7BrDU+IC84C+TBPmfEICYWzuhJulrGkUtAKhJgQzDYItC2t5gAjbZlhBlK6MaVQjI+THUZcfYO3cCAYdVcA=
  file: build/libs/xlr-chef-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-chef-plugin
